# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {
    "AdaptiveSpan": "adaptive_span.ipynb",
    "AlphaChooser": "entmax.ipynb",
    "EntmaxAlpha": "entmax.ipynb",
    "EntmaxBisectFunction": "entmax.ipynb",
    "entmax_bisect": "entmax.ipynb",
    "Lamb": "lamb.ipynb",
    "LayerDrop": "layerdrop.ipynb",
    "LayerDrop_Cross": "layerdrop.ipynb",
    "Lookahead": "lookahead.ipynb",
    "model": "optim_test.ipynb",
    "base_optim": "optim_test.ipynb",
    "optim": "optim_test.ipynb",
}

modules = [
    "adaptive/adaptive_span.py",
    "adaptive/entmax.py",
    "optimizers/lamb.py",
    "adaptive/layerdrop.py",
    "optimizers/lookahead.py",
    "tests/optimizer.py",
]

doc_url = "https://prajjwal1.github.io/fluence/"

git_url = "https://github.com/prajjwal1/fluence/tree/master/"


def custom_doc_links(name):
    return None
