# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://prajjwal1.github.io/fluence/"

git_url = "https://github.com/prajjwal1/fluence/tree/master/"

def custom_doc_links(name):
    return None
