# AUTOGENERATED! DO NOT EDIT! File to edit: optim_test.ipynb (unless otherwise specified).

__all__ = ["model", "base_optim", "optim"]

import torch
import torchvision

# Cell
from ..optimizers.lamb import Lamb
from ..optimizers.lookahead import Lookahead

# Cell
model = torchvision.models.AlexNet()

# Cell
base_optim = Lamb(params=model.parameters(), lr=1e-5, weight_decay=1.2e-6, min_trust=0.25)
optim = Lookahead(base_optimizer=base_optim, k=5, alpha=0.8)

# Cell
model(torch.rand(128, 3, 64, 64))

# Cell
optim.step()
