repository: fastai/nbdev
output: web
topnav_title: nbdev
site_title: nbdev
company_name: fast.ai
description: Writing a library entirely in notebooks
google_search: 000837339549978028235:vh0pq0omtgr
use_math: true
google_analytics:
twitter_username: fastdotai

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor
 
exclude: [vendor]

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars: [home_sidebar]
permalink: pretty
baseurl: /fluence/
#theme: jekyll-theme-cayman

