# AUTOGENERATED! DO NOT EDIT! File to edit: model_test.ipynb (unless otherwise specified).

__all__ = ['params', 'feat', 'pos', 'ques', 'model', 'logits']

# Cell
import torch
from ..models.lxmert import LXMERT_Adaptive

# Cell
params = {'adapt_span_enabled': False, 'attn_span': 1024, 'adapt_span_loss_coeff': 0.000005,
          'adapt_span_ramp': 32, 'adapt_span_init': 0.002, 'adapt_span_cache': True, 'nb_heads': 12,
          'bs': 128, 'mask_size': [20,36], 'sparse_enabled': True, 'num_attention_heads': 4,
          'layer_sizes': {'lang':9,'cross':5,'vision':5}, 'from_scratch': False,
          'layerdrop_enabled': False, 'layerdrop_num_layers': 1, 'max_seq_len': 20}

# Cell
feat = torch.rand(128,36,2048)
pos = torch.rand(128,36,4)
ques = ['Are there any people in this photo?']*128

# Cell
model = LXMERT_Adaptive(3129, params)
logits = model(feat, pos, ques)